version: 0.2
env:
  variables:
    S3_BUCKET: "emis-teacher-transfer-production"
phases:
  install:
    runtime-versions:
      nodejs: 12.x
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli@13.1.2
  build:
    commands:
      - echo Build started on `date`
      - node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build --configuration=production --aot
  post_build:
     commands:
      - aws s3 sync ./dist s3://${S3_BUCKET} --acl 'public-read' --delete
      - aws cloudfront create-invalidation --distribution-id=E19RXN50M6ZCI6 --paths '/*'
      - echo Build completed on `date`
